publish:
  docker:
    repo: smarthouserpi/rpi-relay
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    tag: latest
    file: Dockerfile
    insecure: false
  environment:
    - DOCKER_LAUNCH_DEBUG=true
